In [1]:
import numpy as np

In [5]:
arr2d=np.arange(36).reshape(4,9)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [7]:
arr2d[0: , 0:2]

array([[ 0,  1],
       [ 9, 10],
       [18, 19],
       [27, 28]])

In [9]:
arr2d[[2,3,1,0],[1,6,5,2]]

array([19, 33, 14,  2])

In [11]:
#[30, 16, 20, 4]
arr2d[[3,1,2,0],[3,7,2,4]]

array([30, 16, 20,  4])

In [45]:
#13, 17, 12, 9, 17
#31, 35, 30, 18, 26
arr2d[[1,1,1,1,1,3,3,3,2,2],[4,8,3,0,8,4,8,3,0,8]].reshape(2,5)

array([[13, 17, 12,  9, 17],
       [31, 35, 30, 18, 26]])

In [87]:
arr2d[1:4:2, 2:4]

array([[11, 12],
       [29, 30]])

In [85]:
arr2d[1: :2, [2,3]]

array([[11, 12],
       [29, 30]])

In [89]:
#[13,17,12,9,17]
#31,35,30,27,35]
arr2d[1:4:2,[4,8,3,0,8]]

array([[13, 17, 12,  9, 17],
       [31, 35, 30, 27, 35]])

In [91]:
arr2d[1:4,[4,8,3,0,8]]

array([[13, 17, 12,  9, 17],
       [22, 26, 21, 18, 26],
       [31, 35, 30, 27, 35]])

In [93]:
arr2d[ : ,: :-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [95]:
arr2d[:,-1: : -2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [99]:
arr2d=np.arange(36).reshape(4,9)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [103]:
#22
arr2d[2][4]

22

In [127]:
#0,3,4,6
arr2d[:1:,[0,3,4,6]]

array([[0, 3, 4, 6]])

In [131]:
#1,2,3
arr2d[:1:,[1,2,3]]

array([[1, 2, 3]])

In [139]:
#1,2,3
#10,11,12
#19,20,21
arr2d[:3:,[1,2,3]]

array([[ 1,  2,  3],
       [10, 11, 12],
       [19, 20, 21]])

In [141]:
arr3d=np.arange(64).reshape(4,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [145]:
arr3d[1,2,2]

26

In [147]:
arr3d[3][1][3]

55

In [153]:
arr3d[2:,3:,2:3]

array([[[46]],

       [[62]]])

In [155]:
arr3d[2:,3:,2:]

array([[[46, 47]],

       [[62, 63]]])

q k hum nay kuvh nhi likha hai is liye is ka mutlab hai all select karo tou wo detect nhi ho ga.or jo cheez present hai wo a jai gee.

In [165]:
arr3d[1:2,2:3,2:3]

array([[[26]]])