In [69]:
def divi():
    a=float(input('enter a float'))
    b=float(input('enter a float'))
    if b==0:
        print ('cannot be divided')
    else:
        div=a/b
        print(div)
divi()
        

enter a float 1
enter a float 0


cannot be divided


In [17]:
import numpy as np

In [34]:
arr=np.array([10,20,30,40])
arr


array([10, 20, 30, 40])

In [36]:
arr[2]

30

In [38]:
arr[1:3]

array([20, 30])

In [40]:
arr2=np.array([1,2,3,4])
arr2

array([1, 2, 3, 4])

In [42]:
arr+arr2

array([11, 22, 33, 44])

In [44]:
arr*arr2

array([ 10,  40,  90, 160])

In [46]:
arr

array([10, 20, 30, 40])

In [48]:
arr-arr2

array([ 9, 18, 27, 36])

In [52]:
#mathematical function
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.std(arr))
print(np.concatenate((arr,arr2)))
print(np.repeat(arr,2))

25.0
10
40
100
11.180339887498949
[10 20 30 40  1  2  3  4]
[10 10 20 20 30 30 40 40]


In [54]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr3.shape

(3, 3)

In [61]:
arr3.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
#grenerating arrays 
print(np.arange(0,10,2))
print(np.zeros((3,3)))
print(np.eye(3))

[0 2 4 6 8]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
