In [1]:
import pandas as pd
import numpy as np

In [108]:
# Qno 1 : write a function that checks wheather a even no odd in python
def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"
num = 10
print(f"The number {num} is {check_even_odd(num)}.")

The number 10 is Even.


In [114]:
# Qno 2 : write a function that takes a list of numbers and returns a sum of numbers
def sum_of_numbers(numbers):
    return sum(numbers)
numbers_list = [1, 7, 2, 4, 8]
print(f"The sum of the numbers is {sum_of_numbers(numbers_list)}.")

The sum of the numbers is 22.


In [132]:
# qno3
def verify_user():
    correct_username = "RUBINA"  
    correct_password = "BDA24S"

    while True:
        username = input("Enter username: ")
        password = input("Enter password: ")
        if username == correct_username and password == correct_password:
            print("Access granted!")
            break
        else:
            print("Incorrect username or password. Please try again.")
verify_user()


Enter username:  RUBINA
Enter password:  BDA24S003


Incorrect username or password. Please try again.


Enter username:  RUBINA
Enter password:  BDA24S


Access granted!


In [116]:
# Qno 5: create a numpy array of 10 random integers between 1 and 100 and find the mean and standred diaviation 
import numpy as np
arr= [(1,2,3,4,5,6,7,8,9,10)]
arr

[(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)]

In [126]:
mean=np.mean(arr)
mean

5.5

In [128]:
std=np.std(arr)
std

2.8722813232690143

In [42]:
# qno 8
array= [[1,2,3],[4,5,6]]
array

[[1, 2, 3], [4, 5, 6]]

In [88]:
# QNO6
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [136]:
# qno9
np.random.rand(4,4)

array([[0.20005516, 0.3933143 , 0.76221349, 0.97589755],
       [0.15809301, 0.6688389 , 0.67629806, 0.7971535 ],
       [0.89820983, 0.09933957, 0.81963895, 0.51477829],
       [0.90465925, 0.65593687, 0.06583871, 0.63157335]])

In [138]:
# qno 7
array2=np.arange(1,26)
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])